// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcwk1e_IaI0uWyj5yNOD73uf9NlLN2jNU',
    appId: '1:40549094141:android:018cabc6d55c9633226494',
    messagingSenderId: '40549094141',
    projectId: 'suav-nyiaj-ya',
    storageBucket: 'suav-nyiaj-ya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW2Hz3smeyIeXtaY5k8xx5Qa5X8eeN9N4',
    appId: '1:40549094141:ios:0350477e873e23c2226494',
    messagingSenderId: '40549094141',
    projectId: 'suav-nyiaj-ya',
    storageBucket: 'suav-nyiaj-ya.firebasestorage.app',
    androidClientId: '40549094141-0cdei0mbsnltr1allk2ehl7l5jqj2sat.apps.googleusercontent.com',
    iosClientId: '40549094141-i5g71oeumsts8qr5jmfksjv9h0f2ut90.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaApp',
  );
}
